# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextpass',
            name='tle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.TLE'),
        ),
    ]
