# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tle',
            name='satellitename',
        ),
        migrations.AddField(
            model_name='tle',
            name='name',
            field=models.CharField(default='NAME', max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='SatelliteName',
        ),
    ]
