# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenSat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='mission',
            name='TLE',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
    ]
