# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_azel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azel',
            name='azimuth',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='azel',
            name='elevation',
            field=models.CharField(max_length=15),
        ),
    ]
