# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_nextpass_tle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenSat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='mission',
            name='current_num_passes',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='max_num_passes',
        ),
        migrations.RemoveField(
            model_name='nextpass',
            name='tle',
        ),
        migrations.AlterField(
            model_name='azel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nextpass',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
