# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20170117_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riseTime', models.DateField()),
                ('setTime', models.DateField()),
                ('duration', models.DurationField()),
                ('maxElevation', models.CharField(max_length=15)),
                ('riseAzimuth', models.CharField(max_length=15)),
                ('setAzimuth', models.CharField(max_length=15)),
            ],
        ),
    ]
