# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20170407_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextpass',
            name='mission',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, to='scheduler.Mission'),
        ),
    ]
