# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20170123_1139'),
        ('scheduler', '0004_nextpass'),
    ]

    operations = [
    ]
