# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_merge_20170125_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('priority', models.IntegerField()),
                ('max_num_passes', models.IntegerField()),
                ('current_num_passes', models.IntegerField()),
                ('TLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.TLE')),
            ],
        ),
    ]
